language: julia

os:
  - osx
  - linux

julia:
  - 0.5
  - 0.6
  - nightly

matrix:
  allow_failures:
    - julia: nightly

notifications:
  email: false

script:
  - julia -e 'Pkg.init(); Pkg.clone(pwd()); Pkg.update()'
  - julia -e 'ENV["PYTHON"]=""; Pkg.build("PyCall"); using PyPlot; Pkg.test("EasyPhys", coverage=true)'

after_success:
  - julia -e 'cd(Pkg.dir("EasyPhys")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'
